# build
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:title/
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
layouts_dir: ./_noita
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _noita/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# theme
noita:
  name: 生命力をつくる
  description: 生命力をつくる。
  author:
    name: 生命力をつくる
    url: http://xscey.github.io
  lang: ja
  favicons:
    - /assets/2014/04/21/favicon-152.png
  topbar:
    toggle: Menu
    right:
    #   - name: About
    #     url: /about/
      - name: <i class="fa fa-line-chart" aria-hidden="true"></i> Study
        url: /study/
      - name: <i class="fa fa-cog" aria-hidden="true"></i> Blog
        url: /blog/
      - name: <i class="fa fa-link" aria-hidden="true"></i> Links
        url: /links/
    #   - name: Repository
    #     url: https://github.com/penibelst/jekyll-noita
    #     class: small button
