baseURL = "https://xscey.github.io/note"
languageCode = "ja"
title = "哲学覚書"
FootnoteReturnLinkContents = "↩"
pygmentsUseClasses = true
pygmentsCodefences = true
publishDir = "docs"
preserveTaxonomyNames = true
enableGitInfo = true
